name: build nodejs

on: 
  workflow_dispatch:


jobs:
  build_ios:
    name: iOS
    runs-on: macos-11
    steps:
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '12'
    - uses: actions/checkout@v2
    - name: Show SDK
      run: |
        xcodebuild -version -sdk
    - name: Run build script
      run: |
        cd $GITHUB_WORKSPACE
        sh ./ios.sh
        
  build_android_arm64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install NDK
        run: |
          cd ~
          wget -O NDK -q https://dl.google.com/android/repository/android-ndk-r21b-linux-x86_64.zip
          sudo apt install unzip -y
          unzip -q NDK
      - name: Build
        run: |
          cd $GITHUB_WORKSPACE
          sh ./android.sh arm64
        
  build_android_armv7:
    runs-on: ubuntu-latest
    steps:
      - name: Install gcc-multilib g++-multilib
        run: |
          sudo apt-get install gcc-multilib g++-multilib
      - uses: actions/checkout@v2
      - name: Install NDK
        run: |
          cd ~
          wget -O NDK -q https://dl.google.com/android/repository/android-ndk-r21b-linux-x86_64.zip
          sudo apt install unzip -y
          unzip -q NDK
      - name: Build
        run: |
          cd $GITHUB_WORKSPACE
          sh ./android.sh ${{env.VERSION}} arm
